name: Graphilum
favicon: null
layout_spectrum: 0.6651306101121008
typography_spectrum: 0.079664635239169
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.28833637363277376
  lightness: 0.6132242921739817
  saturation: 0.4398008727002889
  rhythmicContrast: 0.5611024859827012
purpose: []
